---
kind: pipeline
name: default
services:
- name: docker
  image: docker:19.03-dind
  entrypoint:
  - dockerd
  command:
  - --dns=8.8.8.8
  - --dns=8.8.4.4
  - --mtu=1440
  - --log-level=error
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  - name: manifests
    path: /tmp/manifests
steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags
  when:
    event: tag
- name: build
  image: autonomy/build-container:latest
  pull: always
  commands:
  - docker login --username admin --password ANiceAdminPassword registry.k8s.brgl.org
  - docker build . -f Dockerfile -t registry.k8s.brgl.org/met/met-api:0.0.1
  volumes:
  - name: dockersock
    path: /var/run
- name: push
  image: autonomy/build-container:latest
  pull: always
  environment:
    _PASSWORD:
      from_secret: password
    _USERNAME:
      from_secret: user
  commands:
  - docker login --username admin --password ANiceAdminPassword registry.k8s.brgl.org
  - docker push registry.k8s.brgl.org/met/met-api:0.0.1
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
      exclude:
      - pull_request
  depends_on:
  - build

volumes:
- name: dockersock
  temp: {}
- name: manifests
  temp: {}
