appname: 'Met::API'

log_level: 'info'
log_facility: 'daemon'
workers: 8
keepalive: 300
port: 5000
gid: 'met'
uid: 'met'
pidfile: '/run/met-api.pid'
log_file: '/var/log/met-api.log'
plugins:
  Database:
    connections:
      met-db:
        driver: 'Pg'
        host: 'local socket'
        port: '5432'
        username: 'dmolik'
        dbname: 'met-test'
        password: ''
