appname: met

log_level: 'info'
log_facility: 'daemon'
workers: 8
keepalive: 300
port: 5000
gid: 'met'
uid: 'met'
pidfile: '/run/met-api.pid'
log_file: '/var/log/met-api.log'
plugins:
  Database:
    driver: 'Pg'
    host: '127.0.0.1'
    port: 5432
    username: ''
    database: 'met_test'
    password: ''
    dbi_params:
        RaiseError: 1
        AutoCommit: 1
