appname: met

log_level: 'info'
log_facility: 'daemon'
workers: 4
keepalive: 3000
port: 80
gid: 'met'
uid: 'met'
pidfile: '/run/met-api.pid'
log_file: '/var/log/met-api.log'
plugins:
  Database:
    driver: 'Pg'
    host: 'met-db.cluster-cpotngkfolvw.us-east-1.rds.amazonaws.com'
    port: 5432
    username: ''
    database: 'met_db'
    password: ''
    dbi_params:
        RaiseError: 1
        AutoCommit: 1
  "Auth::Github":
    client_id: "abcde"
    client_secret: "abcde"
    scope: ""
    github_auth_failed: "/fail"
    github_auth_success: "/"
